name: Bandit Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit

      - name: Run Bandit
        id: bandit
        run: bandit -r . --format json -o bandit_results.json

      - name: Save Bandit Results as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bandit-results
          path: bandit_results.json